services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      - jenkins
    restart: on-failure
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - ./ansible:/tmp/ansible
    depends_on:
      - docker

  docker:
    image: docker:dind
    ports:
      - 2376:2376
      - 8888:8888
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - jenkins
    privileged: true
    restart: always
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - ./ansible:/tmp/ansible
networks:
  jenkins:

volumes:
  jenkins-docker-certs:
  jenkins-data: