FROM alpine/ansible

# Install Python 3 and pip
RUN apk update && \
  apk add --no-cache python3 py3-pip && \
  # Install pywinrm and requests
  pip3 install --no-cache-dir pywinrm requests

COPY ./ansible/ /tmp/ansible

ENV HOME=/tmp