ungrouped:
  hosts:
    iis:
      ansible_host: 172.27.96.1
      ansible_user: Administrator
      ansible_password: Qazqaz1
      ansible_port: 5985
      ansible_connection: winrm
      ansible_winrm_transport: basic
